### PR TITLE
Prevent page refresh by clicking upload

### PR DESCRIPTION
**Pull request by rickmak**
This is hot fix. I have no idea on why that fakeUpload element exist.

### CODE REVIEW

**Comment by rickmak** [comment]
I have enough of this. @royuen I want someone 1 day to fix it once and for all.

**Comment by rickmak** [comment]
wait, I got error

**Comment by chpapa** [comment]
@rickmak ah, so is this PR good to deploy in production? Or shall wait to have someone work on it on Monday?

**Comment by chpapa** [comment]
Maybe just get someone to properly re do it. Frank is revamping the new form so it is a good time

**Pull request merged**
