### PR TITLE
Make .com.hk email addresses valid on enquiry page

### PR DESCRIPTION
**Pull request by rayrw**
This should fix issue #82 
Make sure to run `blogofile build` to build the site.
Please review it. Thanks.

### CODE REVIEW

**Comment by chpapa** [comment]
@rayrw Actually using an regex to validate email address is known as difficult / almost impossible.

Maybe we could just use something like this instead? https://github.com/mailcheck/mailcheck Don't validate the email, but show suggestion instead. (Or validate only with one @)

Interesting read: https://davidcel.is/posts/stop-validating-email-addresses-with-regex/

**Comment by rayrw** [comment]
@chpapa Nice. I would try to implement this.

**Comment by rayrw** [comment]
I have implemented the email address suggestion functionality.
Notice that I removed the extra validation of email field, because jquery.validate.min.js by default has the basic checking of all input[type=email] elements.

Let's give it a shot.

**Comment by chpapa** [comment]
@rayrw Great works, it works! However it won't close #82 yet, as there is actually another form for submission of prototype enquiry (https://oursky.com/enquiry/prototype), can you send another pull request with a similar fix?

**Pull request merged**
